In [4]:
import numpy as np

In [13]:
# scipy - it is a package that has scintific things in python. 
# numpy is superset and has all features of scipy also

In [14]:
a=range(10)

In [15]:
b=list(a)

In [16]:
type(b)

list

In [17]:
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# np.array is also accepting the generators but only of numbers, not characters

In [19]:
s = ['a','b','c']

In [22]:
s=np.array(s)

In [23]:
# It is accepting the characters but it's performance is downgraded as it has changed its data type

In [24]:
type(s)

numpy.ndarray

In [25]:
arr = np.arange(0,10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [29]:
np.arange(0,11,-2)

array([], dtype=int64)

In [30]:
# step or jump is not allowed to be negative. Generally it is used to operate on Matrix manipulations

In [31]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [32]:
zero_arr = np.zeros(100)

In [33]:
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
# zero_arr is an object of np

In [35]:
zero_arr.shape

(100,)

In [36]:
# .shape is not a function but a member operator

In [37]:
zero_arr.reshape(10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
# all operations are temp and need to be stored to use further

In [40]:
zero_arr.reshape(2,50,order='C').shape

(2, 50)

In [42]:
# By default order is by column 'C'

In [43]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [44]:
# Above call is providing 21 samples in between 0 to 10

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
# eye method is giving us the Identity matrix

In [52]:
# Next is how to generate random samples. Below code generating 10 random numbers in between 0 to 1

In [53]:
np.random.rand(10)

array([0.61389646, 0.45051702, 0.38747352, 0.12339811, 0.34570447,
       0.38161964, 0.0271666 , 0.56134279, 0.65141448, 0.49569331])

In [54]:
# It can also generate a shaped matrix of random numbers

In [55]:
np.random.rand(10,2)

array([[0.14337115, 0.69818534],
       [0.87719244, 0.05301092],
       [0.71581321, 0.83958961],
       [0.01404974, 0.2985622 ],
       [0.43405909, 0.08626547],
       [0.59991404, 0.33937559],
       [0.92902321, 0.71378983],
       [0.33373848, 0.24551092],
       [0.81661461, 0.37823449],
       [0.04813162, 0.64014194]])

In [56]:
# Problem is that it produces the random numbers in uniform distribution

In [59]:
# To generate normal distribution following is the code. But gives Real numbers

In [60]:
np.random.randn(10)

array([-0.21229018,  0.55637764, -0.67098574,  0.1073707 ,  0.26052963,
        0.18613641,  1.07894073,  0.09325806, -0.42186359, -0.31688847])

In [61]:
np.random.randint(10)

9

In [62]:
# Above produces a integer random number from 0 to 10

In [63]:
np.random.randint(0,100,10)

array([78, 46, 79, 20, 63, 98, 53, 97, 12,  4])

In [64]:
# from 0 to 100 give 10 random integers values

In [65]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# OR = any    AND = all  non-zero values

In [69]:
arr.any()

True

In [70]:
arr.all()

False

In [71]:
arr.argmax()

9

In [72]:
arr.dtype

dtype('int64')

In [73]:
zero_arr.dtype

dtype('float64')

In [74]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.max(arr)

9

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [78]:
np.log(arr)

/home/akshatadmin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [79]:
abs(-7)

7

In [80]:
np.ceil(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
np.floor(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])